// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYOlaPuwrpObLr_W2T6EjBfNQiMCjCxuU',
    appId: '1:737945786105:android:7c8254a3e8bae338833428',
    messagingSenderId: '737945786105',
    projectId: 'stridehub-9bd7f',
    storageBucket: 'stridehub-9bd7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPB_guA2LzYCc6xiRrc1fifWvCr9TfU48',
    appId: '1:737945786105:ios:33ab3084d9740118833428',
    messagingSenderId: '737945786105',
    projectId: 'stridehub-9bd7f',
    storageBucket: 'stridehub-9bd7f.firebasestorage.app',
    iosBundleId: 'com.example.stridehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPB_guA2LzYCc6xiRrc1fifWvCr9TfU48',
    appId: '1:737945786105:ios:33ab3084d9740118833428',
    messagingSenderId: '737945786105',
    projectId: 'stridehub-9bd7f',
    storageBucket: 'stridehub-9bd7f.firebasestorage.app',
    iosBundleId: 'com.example.stridehub',
  );
}
